# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02342b0e7a9a1c9717bba8d5fe53d9e56d49ee83031440ab8dda8d83790ded58ec175a656fb8768056e7d39451b3abe88fde20ab04f0ace293175f09e4b0c615

test:
  secret_key_base: 957963a4d1a779fea07e63273d092bbd97355922621eef859d502b3380db5f87e0516d19bd8adeb8947e0c18d443610c45360c3ef1150e441582450422d3df5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
